### ISSUE TITLE
Appending to Log File

### ISSUE THREAD

**Issue by neil1023** [kapadiamush/guilty-spark#1]
In order to append to the log file instead of overwriting the contents of the file, I think you can swap the ">" in your crontab command with a ">>".

`1 */1 * * * [user] ([cd path/to/guilty-spark] && [. path/to/guilty-spark-env] && [path/to/node] guilty.js [> /var/log/guilty-spark/guilty.spark.log])`

Could be:

`1 */1 * * * [user] ([cd path/to/guilty-spark] && [. path/to/guilty-spark-env] && [path/to/node] guilty.js [>> /var/log/guilty-spark/guilty.spark.log])`

I couldn't find this command in any of the files in the repository - otherwise I would have created a pull request where I updated the command. You can test and see whether it works.

**Comment by fullstackhacker** [comment]
Thanks dude! Thought I tried that, makes sense.

**Comment by fullstackhacker** [comment]
Switched it over to `>>` from `>`.
